global:
  scrape_interval: 1s
  evaluation_interval: 1s

scrape_configs:
  - job_name: 'node_exporter'
    ec2_sd_configs:
      - region: "{{ lookup('env', 'AWS_DEFAULT_REGION') }}" 
        access_key: "{{ lookup('env', 'AWS_ACCESS_KEY_ID') }}"
        secret_key: "{{ lookup('env', 'AWS_SECRET_ACCESS_KEY') }}"
        port: 9100